In [13]:
### HW1 Solutions - Vismay Gehlot

In [14]:
import pandas as pd
df = pd.read_csv('world_countries.csv')
df.head(5)

,Country,Region,Population,Area_in_sqrmiles,Pop. Density (per sq. mi.),Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Birthrate,Deathrate
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,"48,0","163,07",700.0,"36,0","46,6","20,34"
1,Albania,EASTERN EUROPE,3581655,28748,"124,6","21,52",4500.0,"86,5","15,11","5,22"
2,Algeria,NORTHERN AFRICA,32930091,2381740,"13,8",31,6000.0,"70,0","17,14","4,61"
3,American Samoa,OCEANIA,57794,199,"290,4","9,27",8000.0,"97,0","22,46","3,27"
4,Andorra,WESTERN EUROPE,71201,468,"152,1","4,05",19000.0,"100,0","8,71","6,25"

In [15]:
df1 = pd.read_csv('world_countries.csv', decimal = ',')
df1.head(5)

,Country,Region,Population,Area_in_sqrmiles,Pop. Density (per sq. mi.),Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Birthrate,Deathrate
0,Afghanistan,ASIA (EX. NEAR EAST),31056997,647500,48.0,163.07,700.0,36.0,46.60,20.34
1,Albania,EASTERN EUROPE,3581655,28748,124.6,21.52,4500.0,86.5,15.11,5.22
2,Algeria,NORTHERN AFRICA,32930091,2381740,13.8,31.00,6000.0,70.0,17.14,4.61
3,American Samoa,OCEANIA,57794,199,290.4,9.27,8000.0,97.0,22.46,3.27
4,Andorra,WESTERN EUROPE,71201,468,152.1,4.05,19000.0,100.0,8.71,6.25

In [17]:
df1.columns
##

Index(['Country', 'Region', 'Population', 'Area_in_sqrmiles',
       'Pop. Density (per sq. mi.)', 'Infant mortality (per 1000 births)',
       'GDP ($ per capita)', 'Literacy (%)', 'Birthrate', 'Deathrate'],
      dtype='object')

In [18]:
print(df1.shape)

(227, 10)

In [19]:
df1.isnull()

,Country,Region,Population,Area_in_sqrmiles,Pop. Density (per sq. mi.),Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Birthrate,Deathrate
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,True,False,False
26,False,False,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
197,False,False,False,False,False,False,False,False,False,False
198,False,False,False,False,False,False,False,False,False,False
199,False,False,False,False,False,False,False,False,False,False
200,False,False,False,False,False,False,False,False,False,False
201,False,False,False,False,False,False,False,False,False,False
202,False,False,False,False,False,False,False,False,False,False
203,False,False,False,False,False,False,False,False,False,False
204,False,False,False,False,False,False,False,False,False,False
205,False,False,False,False,False,False,False,False,False,False
206,False,False,False,False,False,False,False,False,False,False
207,False,False,False,False,False,False,False,False,False,False
208,False,False,False,False,False,False,False,False,False,False
209,False,False,False,False,False,False,False,True,False,False
210,False,False,False,False,False,False,False,False,False,False
211,False,False,False,False,False,False,False,False,False,False
212,False,False,False,False,False,False,False,False,False,False
213,False,False,False,False,False,False,False,False,False,False
214,False,False,False,False,False,False,False,False,False,False
215,False,False,False,False,False,False,False,False,False,False
216,False,False,False,False,False,False,False,False,False,False
217,False,False,False,False,False,False,False,False,False,False
218,False,False,False,False,False,False,False,False,False,False
219,False,False,False,False,False,False,False,False,False,False
220,False,False,False,False,False,False,False,True,False,False
221,False,False,False,False,False,True,False,False,True,True
222,False,False,False,False,False,False,False,True,False,False
223,False,False,False,False,False,True,True,True,True,True
224,False,False,False,False,False,False,False,False,False,False
225,False,False,False,False,False,False,False,False,False,False
226,False,False,False,False,False,False,False,False,False,False

In [20]:
df1.isnull().sum()

Country                                0
Region                                 0
Population                             0
Area_in_sqrmiles                       0
Pop. Density (per sq. mi.)             0
Infant mortality (per 1000 births)     3
GDP ($ per capita)                     1
Literacy (%)                          18
Birthrate                              3
Deathrate                              4
dtype: int64

In [21]:
df2 = df1.dropna(how = 'any')
df2.shape

(206, 10)

In [22]:
df2.describe()

,Population,Area_in_sqrmiles,Pop. Density (per sq. mi.),Infant mortality (per 1000 births),GDP ($ per capita),Literacy (%),Birthrate,Deathrate
count,2.060000e+02,2.060000e+02,206.000000,206.000000,206.000000,206.000000,206.000000,206.000000
mean,3.153934e+07,6.461712e+05,356.841262,37.117864,9698.058252,82.889320,22.319175,9.369709
std,1.234359e+08,1.867309e+06,1703.853230,36.193617,10189.540123,19.701984,11.214983,5.136261
min,7.026000e+03,2.000000e+00,1.800000,2.290000,500.000000,17.600000,7.290000,2.290000
25%,7.715090e+05,1.194050e+04,27.525000,8.457500,1900.000000,71.500000,12.802500,5.820000
50%,5.903757e+06,1.098750e+05,74.200000,23.395000,5550.000000,92.400000,18.845000,7.830000
75%,2.025362e+07,4.722900e+05,181.450000,61.492500,14850.000000,98.000000,29.785000,11.387500
max,1.313974e+09,1.707520e+07,16271.500000,191.190000,55100.000000,100.000000,50.730000,29.740000