Vismay Gehlot

### This homework is due on 10/6 Sunday at 11:59 pm CST

In our lecture on 9/30, we talked about Moneyball and how Data anlysis was used to pick players that are not so famous but more effective  for Okland A's team. In this homework, we will use baseball data to learn some new panda functions and learn more about baseball statistics. This data comes from https://www.baseball-reference.com/
To begin, load the dataset baseball (CSV) into pandas using the read.csv function from pandas, and call the data frame "baseball". 

This dataset contains data concerning a baseball team's performance in a given year. It has the following variables:

Team: A code for the name of the team

League: The Major League Baseball league the team belongs to, either AL (American League) or NL (National League)

Year: The year of the corresponding record

RS: The number of runs scored by the team in that year

RA: The number of runs allowed by the team in that year

W: The number of regular season wins by the team in that year

OBP: The on-base percentage of the team in that year

SLG: The slugging percentage of the team in that year

BA: The batting average of the team in that year

Playoffs: Whether the team made the playoffs in that year (1 for yes, 0 for no)

RankSeason: Among the playoff teams in that year, the ranking of their regular season records (1 is best)

RankPlayoffs: Among the playoff teams in that year, how well they fared in the playoffs. The team winning the World Series gets a RankPlayoffs of 1.

G: The number of games a team played in that year

OOBP: The team's opponents' on-base percentage in that year

OSLG: The team's opponents' slugging percentage in that year

### Problem 1
Make a data frame of number of teams by year. Make a line plot of number of teams with year in x-axis. Is the number of teams increasing by year? (10 points)

In [14]:
import pandas as pd
import numpy as np
import matplotlib as mpt
import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('baseball.csv')

df1 = df.groupby(df['Year'])['Team'].sum().to_frame().reset_index()

df1

    Year                                               Team
0   1962  BALBOSCHCCHWCINCLEDETHOUKCALAALADMINMLNNYMNYYP...
1   1963  BALBOSCHCCHWCINCLEDETHOUKCALAALADMINMLNNYMNYYP...
2   1964  BALBOSCHCCHWCINCLEDETHOUKCALAALADMINMLNNYMNYYP...
3   1965  BALBOSCALCHCCHWCINCLEDETHOUKCALADMINMLNNYMNYYP...
4   1966  ATLBALBOSCALCHCCHWCINCLEDETHOUKCALADMINNYMNYYP...
5   1967  ATLBALBOSCALCHCCHWCINCLEDETHOUKCALADMINNYMNYYP...
6   1968  ATLBALBOSCALCHCCHWCINCLEDETHOULADMINNYMNYYOAKP...
7   1969  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMINMONNYMN...
8   1970  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
9   1971  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
10  1973  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
11  1974  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
12  1975  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
13  1976  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
14  1977  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
15  1978  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
16  1979  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
17  1980  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
18  1982  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
19  1983  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
20  1984  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
21  1985  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
22  1986  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
23  1987  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
24  1988  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
25  1989  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
26  1990  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
27  1991  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
28  1992  ATLBALBOSCALCHCCHWCINCLEDETHOUKCRLADMILMINMONN...
29  1993  ATLBALBOSCALCHCCHWCINCLECOLDETFLAHOUKCRLADMILM...
30  1996  ATLBALBOSCALCHCCHWCINCLECOLDETFLAHOUKCRLADMILM...
31  1997  ANAATLBALBOSCHCCHWCINCLECOLDETFLAHOUKCRLADMILM...
32  1998  ANAARIATLBALBOSCHCCHWCINCLECOLDETFLAHOUKCRLADM...
33  1999  ANAARIATLBALBOSCHCCHWCINCLECOLDETFLAHOUKCRLADM...
34  2000  ANAARIATLBALBOSCHCCHWCINCLECOLDETFLAHOUKCRLADM...
35  2001  ANAARIATLBALBOSCHCCHWCINCLECOLDETFLAHOUKCRLADM...
36  2002  ANAARIATLBALBOSCHCCHWCINCLECOLDETFLAHOUKCRLADM...
37  2003  ANAARIATLBALBOSCHCCHWCINCLECOLDETFLAHOUKCRLADM...
38  2004  ANAARIATLBALBOSCHCCHWCINCLECOLDETFLAHOUKCRLADM...
39  2005  ARIATLBALBOSCHCCHWCINCLECOLDETFLAHOUKCRLAALADM...
40  2006  ARIATLBALBOSCHCCHWCINCLECOLDETFLAHOUKCRLAALADM...
41  2007  ARIATLBALBOSCHCCHWCINCLECOLDETFLAHOUKCRLAALADM...
42  2008  ARIATLBALBOSCHCCHWCINCLECOLDETFLAHOUKCRLAALADM...
43  2009  ARIATLBALBOSCHCCHWCINCLECOLDETFLAHOUKCRLAALADM...
44  2010  ARIATLBALBOSCHCCHWCINCLECOLDETFLAHOUKCRLAALADM...
45  2011  ARIATLBALBOSCHCCHWCINCLECOLDETFLAHOUKCRLAALADM...
46  2012  ARIATLBALBOSCHCCHWCINCLECOLDETHOUKCRLAALADMIAM...

In the next problem, we will use panda's loc function to select rows or columns.
The Pandas loc method enables you to select data from a Pandas DataFrame by label.
It allows you to “$\textbf{loc}$ate” data in a DataFrame. That’s where we get the name loc[]. We use it to locate data. loc has multiple input methods. You enter two inputs in loc function as  $loc[rows you want, columns you want]$.

A single scalar label:  df.loc$[ 1, columnname$] will select row 1(remember row 1 is actually the second row in python) and from that row, it picks the value under the column name. 

A list of labels:  df.loc$[[1,4,5], :]$ will select row 1, row 4, row 5 and all the columns.
Read more about loc function here.
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.loc.html

### Problem 2
Try the code yourdf.loc$[0::10$, 'RS':'BA'], look the the output and explain what just happened. ( 15 points)

In [16]:
df.loc [0::10 , 'RS':'BA']

       RS   RA    W    OBP    SLG     BA
0     734  688   81  0.328  0.418  0.259
10    583  794   55  0.302  0.371  0.236
20    684  680   81  0.317  0.400  0.255
30    731  662   94  0.322  0.413  0.250
40    625  702   72  0.318  0.388  0.247
50    713  529  102  0.323  0.395  0.253
60    713  836   65  0.325  0.416  0.250
70    719  717   80  0.321  0.403  0.254
80    772  640   97  0.332  0.413  0.260
90    720  782   70  0.324  0.418  0.253
100   772  766   87  0.340  0.416  0.268
110   820  709   93  0.334  0.447  0.258
120   720  706   82  0.327  0.415  0.251
130   770  767   84  0.326  0.433  0.254
140   799  680   92  0.332  0.438  0.255
150   712  732   90  0.321  0.413  0.250
160   790  891   71  0.336  0.448  0.267
170   892  821   89  0.354  0.458  0.274
180   773  788   76  0.331  0.424  0.267
190   758  772   78  0.331  0.435  0.264
200   865  812   85  0.347  0.447  0.267
210   696  856   77  0.332  0.421  0.256
220   717  732   83  0.339  0.409  0.272
230   807  726   88  0.348  0.423  0.270
240   836  734   92  0.341  0.429  0.282
250   827  844   72  0.337  0.449  0.272
260   793  742   91  0.343  0.433  0.270
270   736  743   77  0.330  0.413  0.268
280   591  928   43  0.300  0.375  0.240
290   768  643   96  0.327  0.417  0.254
...   ...  ...  ...    ...    ...    ...
940   730  575   97  0.328  0.389  0.269
950   796  709   95  0.344  0.417  0.275
960   675  792   68  0.320  0.389  0.250
970   662  689   82  0.327  0.375  0.273
980   620  768   72  0.303  0.366  0.247
990   676  701   80  0.320  0.373  0.261
1000  614  655   77  0.320  0.357  0.247
1010  668  702   79  0.340  0.364  0.251
1020  643  699   82  0.312  0.385  0.257
1030  603  566   85  0.313  0.353  0.250
1040  486  610   61  0.293  0.332  0.233
1050  775  681  102  0.336  0.436  0.270
1060  680  612   93  0.324  0.365  0.251
1070  743  736   87  0.333  0.415  0.251
1080  790  618   97  0.340  0.408  0.268
1090  595  540   87  0.316  0.359  0.253
1100  671  492  103  0.307  0.385  0.235
1110  583  472   97  0.298  0.346  0.249
1120  683  587   91  0.325  0.376  0.243
1130  695  557  101  0.320  0.379  0.263
1140  719  698   88  0.321  0.406  0.251
1150  571  577   83  0.298  0.368  0.251
1160  569  711   65  0.305  0.340  0.237
1170  707  674   80  0.314  0.371  0.254
1180  621  836   57  0.311  0.379  0.239
1190  715  652   93  0.324  0.392  0.272
1200  615  704   73  0.313  0.353  0.247
1210  747  628   93  0.326  0.403  0.271
1220  745  837   72  0.332  0.386  0.263
1230  774  664   84  0.335  0.394  0.271

[124 rows x 6 columns]

### Problem 3
Create a data frame using loc function so that it displays only the team named BOS in rows and 
the columns RS, RA, W, OBP, SLG, BA, G, OOBP and OSLG. How many times does BOS appear in the data set? (15 points)

In [17]:
df.loc[df.Team=='BOS' , 'RS':'OSLG']

,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG
3,734,806,69,0.315,0.415,0.260,0,NaN,NaN,162,0.331,0.428
33,875,737,90,0.349,0.461,0.280,0,NaN,NaN,162,0.322,0.392
63,818,744,89,0.339,0.451,0.268,0,NaN,NaN,162,0.327,0.399
93,872,736,95,0.352,0.454,0.270,1,3.0,4.0,162,0.335,0.422
123,845,694,95,0.358,0.447,0.280,1,3.0,3.0,162,0.323,0.390
153,867,657,96,0.362,0.444,0.279,1,1.0,1.0,162,0.314,0.392
183,820,825,86,0.351,0.435,0.269,0,NaN,NaN,162,0.343,0.447
213,910,805,95,0.357,0.454,0.281,1,3.0,4.0,162,0.335,0.441
244,949,768,98,0.360,0.472,0.282,1,3.0,1.0,162,0.318,0.408
274,961,809,95,0.360,0.491,0.289,1,4.0,3.0,162,0.327,0.415
304,859,665,93,0.345,0.444,0.277,0,NaN,NaN,162,0.308,0.385
334,772,745,82,0.334,0.439,0.266,0,NaN,NaN,161,0.329,0.393
364,792,745,85,0.341,0.423,0.267,0,NaN,NaN,162,0.322,0.411
394,836,718,94,0.350,0.448,0.278,1,6.0,3.0,162,0.315,0.398
424,876,729,92,0.348,0.463,0.280,1,5.0,4.0,162,NaN,NaN
453,851,857,78,0.352,0.463,0.291,0,NaN,NaN,162,NaN,NaN
480,928,921,85,0.359,0.457,0.283,0,NaN,NaN,162,NaN,NaN
508,686,698,80,0.330,0.395,0.264,0,NaN,NaN,162,NaN,NaN
536,599,669,73,0.321,0.347,0.246,0,NaN,NaN,162,NaN,NaN
562,731,712,84,0.340,0.401,0.269,0,NaN,NaN,162,NaN,NaN
588,699,664,88,0.344,0.395,0.272,1,4.0,3.0,162,NaN,NaN
614,774,735,83,0.351,0.403,0.277,0,NaN,NaN,162,NaN,NaN
640,813,689,89,0.357,0.420,0.283,1,4.0,3.0,162,NaN,NaN
666,842,825,78,0.352,0.430,0.278,0,NaN,NaN,162,NaN,NaN
692,794,696,95,0.346,0.415,0.271,1,3.0,2.0,161,NaN,NaN
718,800,720,81,0.347,0.429,0.282,0,NaN,NaN,163,NaN,NaN
744,810,764,86,0.341,0.441,0.283,0,NaN,NaN,162,NaN,NaN
770,724,775,78,0.335,0.409,0.270,0,NaN,NaN,162,NaN,NaN
796,753,713,89,0.340,0.407,0.274,0,NaN,NaN,162,NaN,NaN
822,757,767,83,0.340,0.436,0.283,0,NaN,NaN,160,NaN,NaN
848,841,711,91,0.344,0.456,0.283,0,NaN,NaN,160,NaN,NaN
874,796,657,99,0.336,0.424,0.267,0,NaN,NaN,163,NaN,NaN
900,859,712,97,0.345,0.465,0.281,0,NaN,NaN,161,NaN,NaN
926,716,660,83,0.324,0.402,0.263,0,NaN,NaN,162,NaN,NaN
950,796,709,95,0.344,0.417,0.275,1,3.0,2.0,160,NaN,NaN
974,696,661,84,0.333,0.377,0.264,0,NaN,NaN,162,NaN,NaN
998,738,647,89,0.338,0.401,0.267,0,NaN,NaN,162,NaN,NaN
1022,691,667,85,0.322,0.397,0.252,0,NaN,NaN,162,NaN,NaN
1046,786,722,87,0.335,0.428,0.262,0,NaN,NaN,162,NaN,NaN
1070,743,736,87,0.333,0.415,0.251,0,NaN,NaN,162,NaN,NaN
1094,614,611,86,0.313,0.352,0.236,0,NaN,NaN,162,NaN,NaN
1114,722,614,92,0.321,0.395,0.255,1,2.0,2.0,162,NaN,NaN
1134,655,731,72,0.310,0.376,0.240,0,NaN,NaN,162,NaN,NaN
1153,669,791,62,0.327,0.400,0.251,0,NaN,NaN,162,NaN,NaN
1173,688,793,72,0.322,0.416,0.258,0,NaN,NaN,162,NaN,NaN
1193,666,704,76,0.312,0.400,0.252,0,NaN,NaN,161,NaN,NaN
1213,707,756,76,0.324,0.403,0.258,0,NaN,NaN,160,NaN,NaN

In [20]:
### you can use yourdf.loc[yourdf.Team=='BOS', columns you want in a list format].

iloc function in pandas is similar to loc function with minor differences. loc uses labels and iloc uses integer positions. For example, yourdf.loc$[0:3, 'BA']$ will pick rows with labels 0 to 3(inluding 0 and 3) and column named BA. If you do yourdf.iloc$[0:3, 8]$ then it prints rows from 0 to 2(note here 3 is excluded) and 8th column which is BA column. Read more about iloc function here.
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.iloc.html

### Problem 4
Use iloc function to produce the same data frame as in problem 3. ( 15 points)

In [18]:
df2 = df['NewLeague']= df.League.map({'NL':'National_League','AL':'American_League'})
df2

0       National_League
1       National_League
2       American_League
3       American_League
4       National_League
5       American_League
6       National_League
7       American_League
8       National_League
9       American_League
10      National_League
11      American_League
12      American_League
13      National_League
14      National_League
15      National_League
16      American_League
17      National_League
18      American_League
19      American_League
20      National_League
21      National_League
22      National_League
23      American_League
24      National_League
25      National_League
26      American_League
27      American_League
28      American_League
29      National_League
             ...
1202    National_League
1203    American_League
1204    National_League
1205    National_League
1206    American_League
1207    National_League
1208    National_League
1209    National_League
1210    National_League
1211    American_League
1212    American_League
1213    American_League
1214    National_League
1215    American_League
1216    National_League
1217    American_League
1218    American_League
1219    National_League
1220    American_League
1221    American_League
1222    National_League
1223    American_League
1224    National_League
1225    National_League
1226    American_League
1227    National_League
1228    National_League
1229    National_League
1230    National_League
1231    American_League
Name: League, Length: 1232, dtype: object

map function maps column values to what you want. For example, if I want to map (change) the league name NL to National_League and AL to American_League and create a new column named NewLeague, I can do that using the code

In [36]:
# yourdf['NewLeague']= yourdf.League.map({'NL':'National_League','AL':'American_League'})

More about map function here.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.map.html

 ### Problem 5
 Use map function to create a new column called 'Selected' and change 'Playoffs' column values from 0 to No and 1 to Yes. Use loc function to filter these 2 columns to check if you did it correclty. (15 points)

In [20]:
df['Selected'] = df.Playoffs.map({0:'No' , 1:'Yes'})

Correlation coefficient: We have talked about correlation and what it means in our lecture. Correlation coefficent is a number that measures how two columns are correlated. There are many kinds of correlation coefficients. We will use Pearson's Correlation coefficient. Given that the variables x and y have data points $x_1, x_2,..., x_n$ and $y_1, y_2,.., y_n$ then the correlation coefficient is defined by $r_{xy}=\dfrac{\displaystyle{\sum_{i=1}^n(x_i-\bar{x})(x_i-\bar{x})}}{\sigma_x\, \sigma_y}$.

$r_{xy}$ is the correlation coefficient. It's value ranges from -1 to 1. Correlation coefficent of -1 means highest possible negative correlation, 0 means no correlation and 1 means highest possible positive correlation.

$\bar{x}$ and $\bar{y}$ are means of x and y respectively.

$\sigma_x$ and $\sigma_y$ are standard deviation of x and y respectuvely. You do not have to worry about complicated looking formula. We will use pandas to find correlation. Let's first prepare the data.

### Problem 6
Use loc or iloc method to filter the original data set to have only the numerical columns
'RS', 'RA', 'W', 'OBP', 'SLG', 'BA', 'G', 'OOBP' and 'OSLG'and give it a new name. (15 points)

In [23]:
df['Numerical'] = df.loc[df.Team=='BOS' , 'RS':'OSLG']

ValueError: Wrong number of items passed 12, placement implies 1

### Problem 7
Find correlations of all the variables with all the variables. Google on how to read a correltion table and answer the following. 

(a) Which two different variables are highly negatively correlated ?

(b) Which two different variables are highly positively correlated ?

(c) Which two different variables are least correlated?

(d) Why does the out put matrix has 1 in the diaginal?

In [25]:
df.corr(method='pearson')

,Year,RS,RA,W,OBP,SLG,BA,Playoffs,RankSeason,RankPlayoffs,G,OOBP,OSLG
Year,1.000000,0.418978,0.412020,0.004138,0.374354,0.536037,0.349397,0.145779,0.385219,0.443967,0.009287,-0.371869,-0.345667
RS,0.418978,1.000000,0.380139,0.511745,0.900492,0.918740,0.827000,0.386628,-0.027687,0.210963,0.075195,0.133981,0.193426
RA,0.412020,0.380139,1.000000,-0.532394,0.326360,0.436527,0.330764,-0.261477,0.399141,0.315128,-0.023369,0.910344,0.909319
W,0.004138,0.511745,-0.532394,1.000000,0.481836,0.401496,0.408716,0.616757,-0.755098,-0.198960,0.105309,-0.634315,-0.568490
OBP,0.374354,0.900492,0.326360,0.481836,1.000000,0.790910,0.851958,0.363890,0.001612,0.175349,0.016563,0.120349,0.153372
SLG,0.536037,0.918740,0.436527,0.401496,0.790910,1.000000,0.790481,0.324713,0.126663,0.271893,0.036770,0.143861,0.210423
BA,0.349397,0.827000,0.330764,0.408716,0.851958,0.790481,1.000000,0.290217,0.035452,0.092684,0.019886,0.187108,0.227808
Playoffs,0.145779,0.386628,-0.261477,0.616757,0.363890,0.324713,0.290217,1.000000,NaN,NaN,0.022208,-0.433572,-0.366744
RankSeason,0.385219,-0.027687,0.399141,-0.755098,0.001612,0.126663,0.035452,NaN,1.000000,0.266906,0.069222,0.097731,0.050111
RankPlayoffs,0.443967,0.210963,0.315128,-0.198960,0.175349,0.271893,0.092684,NaN,0.266906,1.000000,0.007820,0.065808,0.087089
G,0.009287,0.075195,-0.023369,0.105309,0.016563,0.036770,0.019886,0.022208,0.069222,0.007820,1.000000,-0.077055,-0.004188
OOBP,-0.371869,0.133981,0.910344,-0.634315,0.120349,0.143861,0.187108,-0.433572,0.097731,0.065808,-0.077055,1.000000,0.830902
OSLG,-0.345667,0.193426,0.909319,-0.568490,0.153372,0.210423,0.227808,-0.366744,0.050111,0.087089,-0.004188,0.830902,1.000000